Separate javac benchmark to a subproject to sidestep JPMS issue
If a recent JDK is used to run SBT, the JMH source generator
task fails when generating the benchmark sources based on
JavacBenchmark with this failure:

```
Annotation generator had thrown the exception.
java.lang.NoClassDefFoundError: javax/tools/JavaCompiler
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3229)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2335)
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getFields(RFClassInfo.java:81)
	at org.openjdk.jmh.generators.core.BenchmarkGeneratorUtils.getAllFields(BenchmarkGeneratorUtils.java:128)
	at org.openjdk.jmh.generators.core.StateObjectHandler.validateState(StateObjectHandler.java:126)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.validateBenchmark(BenchmarkGenerator.java:246)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:83)
	at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
  | => jat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: javax.tools.JavaCompiler
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 20 more
```

The workaround is to use an older JDK to build the project and only
use the new JDK as the `-jvm` parameter to the `jmh:run` task.

However, for casual use it is convenient to just switch the JDK in the
shell before starting SBT, so this commit makes that possible for the
common case of running ScalacBenchmark.